name: Publish docker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GH_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t docker.pkg.github.com/Mischer/mk-nest-api/mk-nest-api:develop .

      - name: Push Docker image
        run: docker push docker.pkg.github.com/Mischer/mk-nest-api/mk-nest-api:develop