name: Publish docker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to registry
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
            registry: docker.pkg.github.com
            name: docker.pkg.github.com/Mischer/mk-nest-api/mk-nest-api
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.GH_TOKEN}}
            tags: "develop"